export const SET_GAME = 'SET_GAME';
export const CLEAR_GAME = 'SET_GAME';
export const SET_GAME_LOAD_ERROR = 'SET_GAME_LOAD_ERROR';
export const SET_DRAWING_MAP = 'SET_DRAWING_MAP';
export const SET_USER_SUBMITTED_MAP = 'SET_USER_SUBMITTED_MAP';

export const SET_USER = 'SET_USER';
export const SET_USERNAME_NOT_SET = 'SET_USERNAME_NOT_SET';
